#! /usr/bin/bash

NAMEOFURL=${1? Error: please enter a url to open}
NAMEOFADDRESS=${2:-''}

if [ "$NAMEOFURL" == "mail" ]
then 
  firefox https://gmail.com
elif [ "$NAMEOFURL" == "web" ]
then 
  firefox "https://$NAMEOFADDRESS.com"
elif [ "$NAMEOFURL" == "work" ]
then 
     firefox "https://freedcamp.com"
elif [ "$NAMEOFURL" == "search" ]
then 
  firefox "https://google.com/search?q=$2 $3 $4 $5 $6 $7 $8 $9"
elif [ "$NAMEOFURL" == "here" ]
then 
  firefox .
elif [ "$NAMEOFURL" == "." ]
then 
  firefox .
elif [ "$NAMEOFURL" == "phpmyadmin" ]
then 
  firefox "localhost/phpmyadmin"
elif [ "$NAMEOFURL" == "localhost" ]
then 
  firefox "localhost/$2"
elif [ "$NAMEOFURL" == "port" ]
then 
  firefox "localhost:$2"
elif [ "$NAMEOFURL" == "projects" ]
then 
  firefox "file:///var/www/html/projects"
fi
