#! /usr/bin/bash

GOTOLOCATION=${1? Error: Please enter a location}
SUBFOLDER=${2:-''}

if [ "$GOTOLOCATION" == "videos" ]
then 
  cd ~/Videos/$SUBFOLDER 
fi

if [ "$GOTOLOCATION" == "macxprojects" ]
then 
  cd ~/.bitnami/stackman/machines/xampp/volumes/root/htdocs/projects/$SUBFOLDER
fi

if [ "$GOTOLOCATION" == "todos" ]
then
  open ~/.bitnami/stackman/machines/xampp/volumes/root/htdocs/projects/todoManager/index.html
fi

if [ "$GOTOLOCATION" == "projects" ] 
then 
  cd /var/www/html/projects/$SUBFOLDER 
fi

if [ "$GOTOLOCATION" == "macprojects" ]
then
  cd ~/projects/projects/$SUBFOLDER
fi

if [ "$GOTOLOCATION" == "documents" ] 
then 
  cd ~/Documents/$SUBFOLDER 
fi

if [ "$GOTOLOCATION" == "docs" ] 
then 
  cd ~/Documents/$SUBFOLDER 
fi

if [ "$GOTOLOCATION" == "home" ] 
then 
  cd $HOME/$SUBFOLDER 
fi

if [ "$GOTOLOCATION" == "pictures" ] 
then 
  cd ~/Pictures/$SUBFOLDER 
fi

if [ "$GOTOLOCATION" == "downloads" ] 
then 
  cd ~/Downloads/$SUBFOLDER 
fi

if [ "$GOTOLOCATION" == "desktop" ] 
then 
  cd ~/Desktop/$SUBFOLDER 
fi


if [ "$GOTOLOCATION" == "work" ] 
then 
   firefox "https://freedcamp.com"
fi

if [ "$GOTOLOCATION" == "pics" ] 
then 
  cd ~/Pictures/$SUBFOLDER 
fi

if [ "$GOTOLOCATION" == "scripts" ] 
then 
  cd ~/myScripts/$SUBFOLDER 
fi
